name: Publish

on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    name: Validate library publication
    runs-on: ubuntu-latest
    if: github.ref_type != 'tag'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Validate publishing
        run: ./gradlew publishReleasePublicationToMavenCentralRepository

  release:
    name: Release publication
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'

    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}

      ORG_GRADLE_PROJECT_signing.password: ${{ secrets.SIGNING_PASSWORD }}
      ORG_GRADLE_PROJECT_signing.secretKey: ${{ secrets.SIGNING_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4


      - name: Publish to Maven Central
        run: ./gradlew publishReleasePublicationToMavenCentralRepository